FROM node:21

RUN groupadd -r app && useradd -r -g app -d /usr/src/app app

RUN mkdir -p /usr/src/app && chown -R app:app /usr/src/app
WORKDIR /usr/src/app

COPY package*.json ./

USER app

RUN npm ci --omit=dev

COPY . ./

CMD [ "npm", "start" ]
