FROM node:20

RUN groupadd -r app && useradd -r -g app -d /usr/src/app app

RUN mkdir -p /usr/src/app && chown -R app:app /usr/src/app
WORKDIR /usr/src/app

COPY package*.json ./

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
USER root
RUN apt-get update \
    && apt-get install -y wget gnupg ca-certificates \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable

USER app

RUN npm ci --omit=dev

COPY . ./

CMD [ "npm", "start" ]
